### ISSUE TITLE
Add option to serve the coverage report

### ISSUE THREAD

**Issue by fdesjardins** [fdesjardins/coverage-viewer#1]
It's kind of a hassle to have to generate the html over and over. You can use nodemon or similar to regenerate the reports when the coverage output changes, then run browsersync to get livereloading...

I think it'd be better to just serve the reports when the user passes a flag to save them the hassle.

**Comment by patros** [comment]
Pull request #4 means you can use file:// urls and don't need a server.

**Comment by fdesjardins** [comment]
Closed in https://github.com/fdesjardins/coverage-viewer/pull/8.
